### ISSUE TITLE
model evaluation

### ISSUE THREAD

**Issue by mactavish91** [FreedomIntelligence/MLLM-Bench#1]
hello, could you help me to evaluate the result of our model?
[caption.json](https://github.com/FreedomIntelligence/MLLM-Bench/files/13485702/caption.json)

**Comment by Shunian-Chen** [comment]
Sure, please leave an email address here and we'll email you the result.

**Comment by mactavish91** [comment]
> Sure, please leave an email address here and we'll email you the result.

1945834358@qq.com

**Comment by g-h-chen** [comment]
Issue closed as solved.
