### ISSUE TITLE
The submission portal or steps are missing from the readme file...

### ISSUE THREAD

**Issue by zhimin-z** [FreedomIntelligence/MLLM-Bench#3]
![image](https://github.com/FreedomIntelligence/MLLM-Bench/assets/8592144/fedeccfd-aabf-4ee9-ae86-a4b757e4e89d)
Check https://github.com/FreedomIntelligence/MLLM-Bench/blob/679703e2c504c0bf5b2a9ecdb9363375bcb2c9a0/README.md?plain=1#L74

**Comment by Shunian-Chen** [comment]
Thank you very much for your attention to our work. We have just updated the [self-evaluate](https://github.com/FreedomIntelligence/MLLM-Bench?tab=readme-ov-file#self-evaluate) section, hoping it will be helpful to you. 

We will update the upload interface on our official homepage soon. Once we have updated, we will notify you at the first time. Thank you again for your attention. If you have any other questions, feel free to ask.

**Comment by Shunian-Chen** [comment]
Hello Zhimin, we appreciate your patience! We've made some updates to our submission portal and now we're offering a limited number of free daily evaluation slots for GPT-4V. Please take a [look](https://mllm-bench.llmzoo.com/static/submit.html) and see if this is beneficial for you. We eagerly await your feedback.
